server:
  port:8080
pulsar:
  broker-url: pulsar://82.157.51.27:6650
  TopicNames:
    InputTopics:
      UserBehaviorTopic:
        persistent://news/behavior/user-logs
      RawNewsTopic:
        persistent://news/ingestion/news-raw
api:
  token: f59e2e01b849d9780351778038c94c41