# 应用服务 WEB 访问端口
server:
  port:8080
pulsar:
  broker-url:
  TopicNames:
    InputTopics:
      UserBehaviorTopic:
        persistent://news/behavior/user-logs
      RawNewsTopic:
        persistent://news/ingestion/news-raw
api:
  token:


